services:
  cinepilot_front:
    container_name: cinepilot_front
    env_file:
      - .env
    build:
      dockerfile: front.Dockerfile
    ports:
      - "80:80"
      - "5173:5173"
      - "2121:22"
  cinepilot_back_symfony:
    container_name: cinepilot_back_symfony
    env_file:
      - .env
    build:
      dockerfile: back.symfony.Dockerfile
    ports:
      - "8000:8000"
      - "2222:22"
  cinepilot_back_spring:
    container_name: cinepilot_back_spring
    env_file:
      - .env
    build:
      dockerfile: back.spring.Dockerfile
    ports:
      - "8080:8000"
      - "2323:22"
  cinepilot_db:
    image: postgres:latest
    container_name: cinepilot_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cinepilot_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  cinepilot_postgres_data:
